#! /bin/bash

### BEGIN INIT INFO
# Provides:          onioncat
# Required-Start:    tor
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts OnionCat anonymous TOR VPN
# Description:       Starts OnionCat anonymous TOR VPN
### END INIT INFO

set -e

DAEMON=/usr/local/bin/ocat
NAME=OnionCat
DESC="o(nion)cat daemon"
OCATPID=/var/run/ocat.pid
DAEMON_USER=debian-tor
DAEMON_NAME=ocat
ONIONURL=`cat /var/lib/tor/hidden_service/hostname`
ARGS="-u $DAEMON_USER -b -L /var/lib/tor/.ocat/ocat_log $ONIONURL"

case "$1" in
  start)

	echo "Starting $DESC: $NAME..."

	start-stop-daemon --start --quiet \
		--pidfile $OCATPID \
		$NICE \
		--exec $DAEMON -- $ARGS
	echo "done."
	;;

  stop)
	echo -n "Stopping $DESC: "
	pid=`cat $OCATPID 2>/dev/null` || true

	if test ! -f $OCATPID -o -z "$pid"; then
		echo "not running (there is no $OCATPID)."
		exit 0
	fi

	start-stop-daemon --stop --signal INT --quiet --pidfile $OCATPID --name $DAEMON_NAME --user $DAEMON_USER
	;;

  restart)

	$0 stop
	sleep 1
	$0 start
	;;

  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0

