#!/bin/sh

if [ -z "$1" ] ; then
   echo "usage: $0 <hidden_service_hostname>"
   exit 1
fi

TDIR="http://moria.seul.org:9032"
HPID=`echo "$1" | cut -d . -f 1`

rm "$HPID" >/dev/null 2>&1
wget -q "$TDIR/tor/rendezvous/$HPID"

if [ ! -f "$HPID" ] ; then
   echo "could download \"$HPID\" from directory \"$TDIR\""
   exit 1
fi

./getdesc < "$HPID"

