#!/bin/sh

# On Android the interpreter /bin/sh is found in $ANDROID_ROOT which typically
# is /system/bin/sh. Edit the first line appropriatey.

ip address add $OCAT_ADDRESS/$OCAT_PREFIXLEN dev $OCAT_IFNAME
ip route add table local $OCAT_PREFIX/$OCAT_PREFIXLEN dev $OCAT_IFNAME
ip link set $OCAT_IFNAME up 

