Document: onioncat
Title: Debian onioncat Manual
Author: <insert document author here>
Abstract: This manual describes what onioncat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/onioncat/onioncat.sgml.gz

Format: postscript
Files: /usr/share/doc/onioncat/onioncat.ps.gz

Format: text
Files: /usr/share/doc/onioncat/onioncat.text.gz

Format: HTML
Index: /usr/share/doc/onioncat/html/index.html
Files: /usr/share/doc/onioncat/html/*.html
